const data: any[] = [
    {
        "name": "猪肚鸡",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "荷兰豆炒腊肠",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "油麦菜",
        "type": "蔬菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "鱼香肉沫",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "蘑菇三鲜汤",
        "type": "汤",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "红烧鸡翅尖",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "小炒黄牛肉",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": "5",
        "fcategory": 3,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "酸辣鸡胗",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": null,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "红豆排骨汤",
        "type": "汤",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "椒盐肉",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": "5",
        "fcategory": 3,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "苦瓜炒瘦肉沫",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "土豆炖鸡肉",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "韭菜烧猪血",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "外婆菜肉沫",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": null,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "凉拌皮蛋",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "苦瓜炒蛋",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "黄豆芽炒粉条",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "小炒鸡",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": "10",
        "fcategory": 3,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "排骨汤河粉",
        "type": "早餐",
        "active": true,
        "supplykind": 4,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": null,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "干冬菇蒸鸡",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "小炒肉",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": "5",
        "fcategory": 3,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "粉丝蒸虾仁",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "姜葱炒花甲",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "玉米粒炒火腿",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "酸菜炒肥肠",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "蒸茄子",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "金针菇蒸肉沫",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "丝瓜炖肚条",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "水煮牛肉",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": "5",
        "fcategory": 3,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "干香菇焖鸭",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "土鸡栗子汤",
        "type": "汤",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "木耳焖肉",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "莲子猪心汤",
        "type": "汤",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "鲜海鲜菇煮肉",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "沫烧冬瓜",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "凉瓜牛肉",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "土豆丝炒瘦肉沫",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": "5",
        "fcategory": 3,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "全麦面包",
        "type": "小吃",
        "active": true,
        "supplykind": 4,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": null,
        "fpreset": false,
        "stored": 2
    },
    {
        "name": "红烧罗非全鱼",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "剁椒三文鱼头",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "豆腐烧鱼块",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "千张炒瘦肉沫",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "烤带鱼",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "莴笋炒肉",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "西芹炒牛肉",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "扇贝冬瓜汤",
        "type": "汤",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "红烧魔芋豆腐",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": null,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "香菇炖猪脚",
        "type": "菜",
        "active": false,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "铁盘焗鸡肉",
        "type": "菜",
        "active": true,
        "supplykind": 2,
        "auto": 0,
        "fprocess_cost": null,
        "fcategory": 1,
        "fpreset": false,
        "stored": null
    },
    {
        "name": "坚果奶昔",
        "type": "小吃",
        "active": true,
        "supplykind": 2,
        "auto": 1,
        "fprocess_cost": null,
        "fcategory": null,
        "fpreset": false,
        "stored": null
    }
] ;

export default data;